ActionMailer::Base.delivery_method = :smtp
ActionMailer::Base.smtp_settings = {
  :address              => "smtp.gmail.com",
  :port                 => 587,
  :domain               => 'shopnochura.com',
  :user_name            => 'khaledimran.tanim@gmail.com',
  :password             => 'tanimotogj456',
  :authentication       => 'plain',
  :enable_starttls_auto => true  }